version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - '9999:9999'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=8fASdf932fdDF2